version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Arudchayan"
    labels:
      - "dependencies"
    versioning-strategy: increase
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    assignees:
      - "Arudchayan"
    labels:
      - "dependencies"
